---
title: "The Top of Both Cultures"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    storyboard: true
---

```{r setup, include=FALSE}
library(flexdashboard)
```

Main idea of the research {data-width=650}
-----------------------------------------------------------------------

### What is my research?

```{r}

```
> My Music Corpus

<p>
The corpus I chose are two of my personal playlists of the collection of the top rated English and Chinese speaking artists that influenced the industry and culture. From these artists, I chose my personal favourites, which are also their magnum opuses. Luckily, for both playlists, they have an even number of 109 tracks. Since the Western music greatly influences the musical culture across the world, China is not an exception. Chinese modern music culture was influenced by Western music relatively late, and Chinese musicians were mainly learning, absorbing and fusing it with local taste, it is can be interesting to find out the general similarities and differences for both cultures. For this reason, I would like to research on what are the common elements that makes these albums so popular and influential, and how do these differences affect people from both cultures’ most popular taste on music. For English culture, I expect people might love music with higher danceability, but for Chinese culture, people might love softer and more melodic songs. The sub-cultural groups are huge for both cultures and it is “the variable” I’m unsure about. I think my corpus is quite representative since I had compared many ranking lists to set my final selection of most influential artists and tracks from them are also their well-known works. The limitation of this corpus might be the scale of involved artists. There are still quite a lot of artists I love can be in the list, but due to the time and the capacity of workload on my laptop, I can only select a few of them. Since I chose the artist first, and select albums afterwards, the genres from these albums from different artists are diverse, so each track can be seem as typical or atypical. It is also an interesting point for this study!:</p>

<p>
<ol>Chinese:
<li> Jay Chou - Fantasy </li>
<li> Tat Ming Pair - Nerves </li>
<li> Lo Ta-yu - Zhi Hu Zhe Ye </li>
<li> Jacky Cheung - Goodbye Kiss </li>
<li> Cui Jian -  Rock ’n’ Roll on the New Long March </li>
<li> Beyond - Beyond - 25th Anniversary </li>
<li> Dou Wei - Black Dream </li>
<li> David Tao - David Tao </li>
<li> Faye Wong - Sing and Play </li>
</ol>
</p>

<p>
<ol>English:
<li> Joy Division - Unknown Pleasures (1979) </li>
<li> The Beatles - Revolver (1966) </li>
<li> Nirvana – Nevermind (1991) </li>
<li> DJ Shadow - Endtroducing (1996) </li>
<li> Pink Floyd - Dark Side Of The Moon (1973) </li>
<li> Radiohead - OK Computer (1997) </li>
<li> Led Zeppelin - Led Zeppelin IV </li>
<li> Daft Punk - Discovery </li>
</ol>
</p>



-----------------------------------------------------------------------

### Fun Visualizations

```{r}
library(tidyverse)
library(spotifyr)
library(compmus)

girl <-
  get_tidy_audio_analysis("6rfWywxF7VQEBig0KfGOpU") |>
  select(segments) |>
  unnest(segments) |>
  select(start, duration, pitches)

girl |>
  mutate(pitches = map(pitches, compmus_normalise, "euclidean")) |>
  compmus_gather_chroma() |> 
  ggplot(
    aes(
      x = start + duration / 2,
      width = duration,
      y = pitch_class,
      fill = value
    )
  ) +
  geom_tile() +
  labs(x = "Time (s)", y = NULL, fill = "Magnitude") +
  theme_minimal() +
  scale_fill_viridis_c()



Shi <-
  get_tidy_audio_analysis("2oSyibxNEOnHUYh1J0xNYX") |>
  select(segments) |>
  unnest(segments) |>
  select(start, duration, pitches)

Shi |>
  mutate(pitches = map(pitches, compmus_normalise, "euclidean")) |>
  compmus_gather_chroma() |> 
  ggplot(
    aes(
      x = start + duration / 2,
      width = duration,
      y = pitch_class,
      fill = value
    )
  ) +
  geom_tile() +
  labs(x = "Time (s)", y = NULL, fill = "Magnitude") +
  theme_minimal() +
  scale_fill_viridis_c()

Bohe <-
  get_tidy_audio_analysis("4u7EnebtmKWzUH433cf5Qv") |>
  select(segments) |>
  unnest(segments) |>
  select(start, duration, pitches)

Bohe |>
  mutate(pitches = map(pitches, compmus_normalise, "euclidean")) |>
  compmus_gather_chroma() |> 
  ggplot(
    aes(
      x = start + duration / 2,
      width = duration,
      y = pitch_class,
      fill = value
    )
  ) +
  geom_tile() +
  labs(x = "Time (s)", y = NULL, fill = "Magnitude") +
  theme_minimal() +
  scale_fill_viridis_c()


Time <-
  get_tidy_audio_analysis("4xHWH1jwV5j4mBYRhxPbwZ") |>
  select(segments) |>
  unnest(segments) |>
  select(start, duration, pitches)

Time |>
  mutate(pitches = map(pitches, compmus_normalise, "euclidean")) |>
  compmus_gather_chroma() |> 
  ggplot(
    aes(
      x = start + duration / 2,
      width = duration,
      y = pitch_class,
      fill = value
    )
  ) +
  geom_tile() +
  labs(x = "Time (s)", y = NULL, fill = "Magnitude") +
  theme_minimal() +
  scale_fill_viridis_c()

```

***

### Some Conclusion and discussions

```{r}

```

